### ISSUE TITLE
pre-trained models on Youtobe-UGC

### ISSUE THREAD

**Issue by cs19469** [Tlili-ahmed/2BiVQA#12]
Hello, I would like to inquire if it is possible to provide the pre-trained models on UGC.

**Comment by atelili** [comment]
Hello, I regret to inform you that I no longer possess the pre-trained models. However, you can train it by yourself and if you encounter any difficulties, please don't hesitate to contact me.

**Comment by cs19469** [comment]
Yeah, thank you for your help.
