### ISSUE TITLE
How to generate konvid.csv for our case?

### ISSUE THREAD

**Issue by muhammad-faizan-122** [Tlili-ahmed/2BiVQA#13]
I run the feature extraction script with following command, but don't know how to generate that konvid.csv for further processing. Please help me out.
```
!python3 extract_features.py -v /content/drive/MyDrive/videos -f konvid.csv -o 0.2 -fl 0
```

**Comment by atelili** [comment]
Hello, we will find that CSV file when you download the dataset https://database.mmsp-kn.de/konvid-1k-database.html
