### ISSUE TITLE
What was the best score of the size nb_frames and overlap?

### ISSUE THREAD

**Issue by circlebig** [Tlili-ahmed/2BiVQA#14]
Hi, may you tell me the number of overlap and nb_frames?

**Comment by Ahmed-Telili** [comment]
Hello, the number of frame was set to 30 and the overlap to 0.2

**Comment by circlebig** [comment]
Thank you very much. May I ask some questions?

First, did you extract and train all the features of Konvid and then test on test patch features?

Second, if I set nb_frames 30 and overlap 0.2, the shape of feature is (2880, 2560) (backbone: mnasnet)
2880 might be len of video(240)* patches.
Did your computer work well in training that features?
My computer spec is i9-12900k, rtx3090, ram 78GiB. It seems 2880 is too big to train.

**Comment by Ahmed-Telili** [comment]
Hi @circlebig, we used a pretraining backbone to extract feature from dataset, we used 25 as number of patches. So the shape of the features will be (30, 25, 2560), to avoid resource limitation, you can process the dataset image by image for features extraction.

**Comment by circlebig** [comment]
Thank you. Was your number of features same as number of videos?

**Comment by Ahmed-Telili** [comment]
Welcome ;) The number of features depends solely on the backbone. For MnasNet, each video will have features of shape (30, 25, 2560)

**Comment by circlebig** [comment]
Oh, I mean the number of features. For example, there are 1200 videos in Konvid data. So my number of features is 1200. Is is same as yours? 1200

**Comment by Ahmed-Telili** [comment]
It does not depend on the number of videos. For each video, you will get a tensor of shape (30, 25, 2560) representing its features. If you will compute the features of the Konvid dataset (1200 videos), you will get 1200 tensors.

**Comment by circlebig** [comment]
1200 tensors right. Thank you .
