### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by Xiaocong6** [Tlili-ahmed/2BiVQA#2]
I am interested in your work and would like to read the paper for more information. When will the paper be open sourced? Thanks~

**Comment by atelili** [comment]
Thank you for your interest in our work, the paper will be released ASAP (probably next month)

**Comment by Xiaocong6** [comment]
Thanks~~

**Comment by Xiaocong6** [comment]
> Thank you for your interest in our work, the paper will be released ASAP (probably next month)

hi~when will the paper is released?

**Comment by atelili** [comment]
@Xiaocong6 , Hello, sorry for the late reply, you can found the paper on this link: https://arxiv.org/abs/2208.14774
