### ISSUE TITLE
how to change the input size in pretrained model?

### ISSUE THREAD

**Issue by Xiaocong6** [Tlili-ahmed/2BiVQA#3]
hi~
I would like to do some experiments with your code. I want to change the input size of (30, 25, 2048), but in the pre-trained model 'res-bi-sp_koniq.h5', this input seems to be fixed, how can I get my own pre-trained model with arbitrary size?

**Comment by atelili** [comment]
Hello, 
Thank you for your interest in our work.
You can change the number of frame N:  Input size ( N, 25, 2048). However, you can't change the number of patches (25) yet, but I will add soon a script to do that.
Kind regards,

**Comment by atelili** [comment]
Hello, you can find a script named spatial_train.py. However, it is recommended to train the spatial pooling module on an IQA dataset.
