### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by usutdzxych** [Tlili-ahmed/2BiVQA#4]
What causes the model training not to stop

**Comment by usutdzxych** [comment]
![image](https://user-images.githubusercontent.com/81990359/192131084-38dfee91-1f68-4f80-84dd-ae2b1e8f2116.png)

**Comment by atelili** [comment]
Hello, you need to specify arguments before (which folder contains data...), type python spatial_train.py -h for more details.

**Comment by usutdzxych** [comment]
I have set all the parameters. I don't think it's a problem with parameter settings

**Comment by atelili** [comment]
can you send me these parameter ?

**Comment by usutdzxych** [comment]
!python3 spatial_train.py -p 16 -b 16

**Comment by atelili** [comment]
Did you extract the features  with extract_features.py ?

**Comment by usutdzxych** [comment]
yes，I tried 4 videos of myself for training, but no epoch appeared

**Comment by usutdzxych** [comment]
I tried 4 videos of myself for training, but no epoch appeared

**Comment by atelili** [comment]
To train 2BiVQA you need to execute  End2End_train.py, spatial_train.py is used only to train the spatial pooling module and it works only with images not videos.

**Comment by atelili** [comment]
The spatial pooling module is trained on Koniq10k database, you can use it directly with End2End_train.py, I will add further arguments and comments to clarify this point. Thanks.

**Comment by usutdzxych** [comment]
Thank you for your answer; But I had trained with  End2End_train.py，it  also happens that no epoch appeared

**Comment by atelili** [comment]
![image](https://user-images.githubusercontent.com/63148576/192289911-4c449715-add9-47b0-9cf9-9d4d4ada1921.png)
There is no issues with the train.

**Comment by atelili** [comment]
> yes，I tried 4 videos of myself for training, but no epoch appeared

Here you tried 4 videos, while you specify batch_size as 16

**Comment by atelili** [comment]
I will close this issue, if you still face the some problem you can contact me at **atelili@insa-rennes.fr** and we can organize a meeting on zoom or google meet.

**Comment by usutdzxych** [comment]
After reading your reply, I think it may be the problem of environment and data, because my data is run on Google's Colab. Can you upload the Colab version, including the running data?

**Comment by atelili** [comment]
You can find a brief demo here: https://drive.google.com/drive/folders/1O4xajRa71K7fkmdjGvLDuNbX8ATdZ_hP?usp=sharing

**Comment by usutdzxych** [comment]
Thank you for your work. I don't know how long your dataset video is? If possible, can you upload part of the video in Colab and extract features

**Comment by atelili** [comment]
We used 3 datasets, you can find details in [our paper](https://arxiv.org/abs/2208.14774).
I have already uploaded 10 videos features in the drive.

**Comment by usutdzxych** [comment]
I have no more questions. Thank you for your help. Good luck to you.

**Comment by usutdzxych** [comment]
I want to reproduce your paper, but I can't find the dataset you synthesized from three dataset in the paper, including videos and MOS.Can you send me your new dataset including videos and MOS?

**Comment by atelili** [comment]
You can find all details in our paper.
"We also used these three datasets to create a fourth dataset, which is the union of them after MOS calibration using the Iterative Nested Least Squares Algorithm (INSLA)"
