### ISSUE TITLE
extract_feaures

### ISSUE THREAD

**Issue by Nirvana-feng** [Tlili-ahmed/2BiVQA#5]
Hello, I want to ask if you want to extract and save video frames locally in advance. I tried to extract and save the video frame to the local, but the following error occurred when running
![image](https://user-images.githubusercontent.com/67857885/197203849-4f8afe4b-ebd7-436a-9931-78ebd7240474.png)It should be that I didn't read the image, so first ask me what I should do to extract features. This is the video frame I extracted
![image](https://user-images.githubusercontent.com/67857885/197204138-111e5fb1-7a80-4b16-972c-beb79069cb7a.png)The underlined part is the name of the video

**Comment by atelili** [comment]
Hello, can you send me  arguments used with features_extraction.py ?

**Comment by Nirvana-feng** [comment]
![image](https://user-images.githubusercontent.com/67857885/197205176-a9f5a905-2b11-4591-9f8c-d85af2060a94.png)
The underlined part is the file path of the video

**Comment by atelili** [comment]
The problem in the path of videos that's why the script can't read them, can you please send me your csv file konvid.csv ?

**Comment by Nirvana-feng** [comment]
![image](https://user-images.githubusercontent.com/67857885/197208544-b916ba22-0195-4c49-915e-b4a5d054c3a1.png)This is a csv file

**Comment by atelili** [comment]
you have to add the extension for all videos (.mp4) in the csv file.

**Comment by Nirvana-feng** [comment]
Okay, thank you I'll try

**Comment by atelili** [comment]
You're welcome, please close this issue if that works.

**Comment by Nirvana-feng** [comment]
It's still not possible. Is it my file address

**Comment by Nirvana-feng** [comment]
It's still not possible. Is it my file address

**Comment by atelili** [comment]
The problem in your csv file, or in your folder path,  the script cannot read the path of your videos, in fact, it takes the path, in your case: F:\\data\\koNViD_1k and add '/' + the name of the video, so it has to be like this: F:\\data\\koNViD_1k\16515618.mp4.

**Comment by Nirvana-feng** [comment]
When I set flag=0, the program starts running. When flag=1, the same error as before will be reported. Is it because the file path should be changed to the video frame saving path when flag=1
![image](https://user-images.githubusercontent.com/67857885/197216032-cb74fc90-f06c-4bf2-bed3-c27031e0d81e.png)

**Comment by atelili** [comment]
Ok, if you use it on videos, the flag should remain 0. This is mentioned in the help when you type extract_features.py -h .
I will close this issue, don't hesitate to contact me if you have any problems. 
Kind regards,

**Comment by Nirvana-feng** [comment]
Okay Thank you

**Comment by atelili** [comment]
Please make star on the repository if you find it interesting
