### ISSUE TITLE
Extract features

### ISSUE THREAD

**Issue by Nirvana-feng** [Tlili-ahmed/2BiVQA#8]
I have set the flag to 1, but there is still a problem. I extracted the video in KoNViD into an image and saved it. Excuse me, this is how it works

**Comment by atelili** [comment]
Have you prepared a csv file containing all the images with their labels?

**Comment by Nirvana-feng** [comment]
The image here refers to all the images extracted from the video. If so, the quality scores of the images extracted from a video are the same.

**Comment by Nirvana-feng** [comment]
For example, the quality score of the image extracted from the video named 3339962845.mp4 in the following figure is the video quality score

**Comment by atelili** [comment]
can you send to me the output of the script ?

**Comment by Nirvana-feng** [comment]
![image](https://user-images.githubusercontent.com/67857885/197971423-6d1a75c7-9a72-49e4-ad71-be8b4f1da71b.png)
This is the image I extracted from the video.

**Comment by atelili** [comment]
can you prepare a notebook so i can  find out what is the problem ?

**Comment by Nirvana-feng** [comment]
Sorry, I don't understand what you mean. I don't know what documents you want me to provide

**Comment by Nirvana-feng** [comment]
I can see the contents in the. csv file when you set flag to 1

**Comment by atelili** [comment]
No,I would like to see the error, if you are available we can make a quick meeting on google meet

**Comment by Nirvana-feng** [comment]
We may not be able to contact you through google meet. Can you tell us if you can contact us through an email

**Comment by atelili** [comment]
there is my email: atelili@insa-rennes.fr 
I will close this Issue because the code works well, you are always welcome to contact me on my email
